---
- name: Install nut client
  ansible.builtin.package:
    name: "{{ nut_client_package }}"
    state: present
  tags: packages

- name: Configure upsmon.conf
  ansible.builtin.template:
    src: upsmon.conf.j2
    dest: "{{ nut_config_path }}/upsmon.conf"
    owner: root
    group: "{{ nut_user }}"
    mode: '0640'
  notify:
    - restart nut-monitor
  tags: nut
