---
- name: Configure nut.conf
  ansible.builtin.template:
    dest: "{{ nut_config_path }}/nut.conf"
    src: nut.conf.j2
    owner: root
    group: "{{ nut_user }}"
    mode: '0640'
  register: nut_conf_result
  tags: nut

- name: Install usbutils
  ansible.builtin.package:
    name: usbutils
    state: present
  tags: packages
