---
- include_vars: "{{ansible_distribution}}.yml"

- import_tasks: server.yml
  when: >
    nut_nut_conf.MODE == 'netserver' or
    nut_nut_conf.MODE == 'standalone'

- import_tasks: client.yml
  when: >
    nut_nut_conf.MODE == 'netserver' or
    nut_nut_conf.MODE == 'netclient' or
    nut_nut_conf.MODE == 'standalone'

- import_tasks: common.yml
  when: >
    nut_nut_conf.MODE == 'netserver' or
    nut_nut_conf.MODE == 'netclient' or
    nut_nut_conf.MODE == 'standalone'

- import_tasks: state.yml
