---
- name: install nut server
  package: >
    name={{nut_server_package}}
    state=latest
  tags: nut

- name: configure ups.conf
  template: >
    src=ups.conf.j2
    dest={{nut_config_path}}/ups.conf
    owner=root
    group={{nut_user}}
    mode=0644
  notify:
    - restart nut-server
    - restart nut-driver
  tags: nut

- name: configure upsd.conf
  template: >
    src=upsd.conf.j2
    dest={{nut_config_path}}/upsd.conf
    owner=root
    group={{nut_user}}
    mode=0644
  notify:
    - restart nut-server
  tags: nut

- name: configure upsd.users
  template: >
    src=upsd.users.j2
    dest={{nut_config_path}}/upsd.users
    owner=root
    group={{nut_user}}
    mode=0640
  notify:
    - restart nut-server
  tags: nut

- name: install udev rules
  copy: >
    src=files/52-nut-usbups.rules
    dest=/etc/udev/rules.d/52-nut-usbups.rules
    mode=0644
    group=root
    owner=root
  notify:
    - restart nut-driver
  tags: nut

- name: enable nut.target
  ansible.builtin.systemd_service:
    name: nut.target
    enabled: true
    daemon_reload: true
  tags: nut

- name: enable nut-driver.target
  ansible.builtin.systemd_service:
    name: nut-driver.target
    enabled: true
    daemon_reload: true
  tags: nut

- name: enable nut-server.service
  ansible.builtin.systemd_service:
    name: nut-server.service
    enabled: true
    daemon_reload: true
  tags: nut

- name: enable nut-monitor.service
  ansible.builtin.systemd_service:
    name: nut-monitor.service
    enabled: true
    daemon_reload: true
  tags: nut
