---
- name: Ensure nut-driver started
  ansible.builtin.service:
    name: "{{ nut_driver_service }}"
    state: started
    enabled: true
  when: >
    nut_nut_conf.MODE == 'netserver' or
    nut_nut_conf.MODE == 'standalone'
  tags: nut

- name: Ensure nut-monitor started
  ansible.builtin.service:
    name: "{{ nut_client_service }}"
    state: started
    enabled: true
  when: >
    nut_nut_conf.MODE == 'netserver' or
    nut_nut_conf.MODE == 'netclient' or
    nut_nut_conf.MODE == 'standalone'
  tags: nut

- name: Ensure nut-server started
  ansible.builtin.service:
    name: "{{ nut_server_service }}"
    state: started
    enabled: true
  when: >
    nut_nut_conf.MODE == 'netserver' or
    nut_nut_conf.MODE == 'standalone'
  tags: nut
